spring:
  application:
    name: authapi

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  error:
    include-stacktrace: ALWAYS

jwt:
  secret: ${JWT_SECRET:12345678913456789123456789123456789}
  expiration: ${JWT_EXPIRATION:86400000}